=== Celebrate-future/tis/tis-console/webapp/dtd/solrschema.dtd
<!--~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~   or more contributor license agreements.  See the NOTICE file
  ~   distributed with this work for additional information
  ~   regarding copyright ownership.  The ASF licenses this file
  ~   to you under the Apache License, Version 2.0 (the
  ~   "License"); you may not use this file except in compliance
  ~   with the License.  You may obtain a copy of the License at
  ~
  ~       http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~   Unless required by applicable law or agreed to in writing, software
  ~   distributed under the License is distributed on an "AS IS" BASIS,
  ~   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~   See the License for the specific language governing permissions and
  ~   limitations under the License.
  -->

<!ELEMENT schema (types|fields|uniqueKey|sharedKey?|defaultSearchField?|similarity?|solrQueryParser?|copyField*)+>

<!ATTLIST schema name CDATA #REQUIRED>
<!ATTLIST schema version CDATA #REQUIRED>
<!ATTLIST schema indexMaker CDATA #IMPLIED>
<!ATTLIST schema docMaker CDATA #IMPLIED>

<!ELEMENT types (fieldType+)>
<!ELEMENT fieldType (analyzer*)>

<!ATTLIST fieldType name CDATA #REQUIRED>
<!ATTLIST fieldType class CDATA #REQUIRED>
<!ATTLIST fieldType positionIncrementGap CDATA #IMPLIED>
<!ATTLIST fieldType sortMissingLast (true|false) "true">
<!ATTLIST fieldType omitNorms (true|false) "true">
<!ATTLIST fieldType precisionStep CDATA #IMPLIED>
<!ATTLIST fieldType autoGeneratePhraseQueries (true|false) #IMPLIED>
<!ATTLIST fieldType tokenized (true|false) #IMPLIED>
<!ATTLIST fieldType omitTermFreqAndPositions (true|false) #IMPLIED>
<!ATTLIST fieldType omitPositions (true|false) #IMPLIED>
<!ATTLIST fieldType dimension CDATA  #IMPLIED>
<!ATTLIST fieldType subFieldSuffix  CDATA  #IMPLIED>
<!ATTLIST fieldType units  CDATA  #IMPLIED>

<!ATTLIST fieldType maxDistErr  CDATA  #IMPLIED>
<!ATTLIST fieldType distErrPct  CDATA  #IMPLIED>
<!ATTLIST fieldType spatialContextFactory   CDATA  #IMPLIED>
<!ATTLIST fieldType distCalculator   CDATA  #IMPLIED>
<!ATTLIST fieldType prefixTree  CDATA  #IMPLIED>
<!ATTLIST fieldType autoIndex  (true|false)  #IMPLIED>
<!ATTLIST fieldType distanceUnits   CDATA  #IMPLIED>


<!ATTLIST fieldType fieldSplitor  CDATA  #IMPLIED>
<!ATTLIST fieldType valueSplitor  CDATA  #IMPLIED>
<!ATTLIST fieldType prefix  CDATA  #IMPLIED>
<!ATTLIST fieldType filterKey  CDATA  #IMPLIED>
<!ATTLIST fieldType storeIncludes  CDATA  #IMPLIED>
<!ATTLIST fieldType docvalueKey  CDATA  #IMPLIED>


<!ATTLIST fieldType startTier  CDATA  #IMPLIED>
<!ATTLIST fieldType endTier  CDATA  #IMPLIED>

<!ATTLIST fieldType maxLevels  CDATA  #IMPLIED>
<!ATTLIST fieldType geo (true|false) #IMPLIED>

<!ATTLIST fieldType postingsFormat CDATA  #IMPLIED>
<!ATTLIST fieldType subFieldType CDATA  #IMPLIED>
<!ATTLIST fieldType valIndex  CDATA  #IMPLIED>

<!ATTLIST fieldType docValues CDATA  #IMPLIED>

<!ELEMENT analyzer (tokenizer|filter|charFilter)*>
<!ATTLIST analyzer
  type (index|query) #IMPLIED
  class CDATA        #IMPLIED>

<!ELEMENT charFilter EMPTY>
<!ATTLIST charFilter
   class CDATA #REQUIRED>

<!ATTLIST charFilter pattern  CDATA  #IMPLIED>
<!ATTLIST charFilter replacement  CDATA  #IMPLIED>
<!ATTLIST charFilter replace  CDATA  #IMPLIED>
<!ATTLIST charFilter min  CDATA  #IMPLIED>
<!ATTLIST charFilter max  CDATA  #IMPLIED>


<!ELEMENT tokenizer EMPTY>
<!ATTLIST tokenizer
   class CDATA #REQUIRED
   group CDATA #IMPLIED
   pattern CDATA #IMPLIED
   isMaxWordLength (true|false) #IMPLIED
   type CDATA  #IMPLIED
   dicPath CDATA  #IMPLIED
   mode CDATA #IMPLIED
   minGramSize CDATA #IMPLIED
   maxGramSize CDATA #IMPLIED
>



<!ELEMENT filter EMPTY>
<!ATTLIST filter class CDATA #REQUIRED>
<!ATTLIST filter minGramSize  CDATA  #IMPLIED>
<!ATTLIST filter maxGramSize  CDATA  #IMPLIED>

<!ATTLIST filter direction  CDATA  #IMPLIED>
<!ATTLIST filter id  CDATA  #IMPLIED>
<!ATTLIST filter side CDATA  #IMPLIED>
<!ATTLIST filter rules CDATA  #IMPLIED>

<!ATTLIST filter withOriginal CDATA  #IMPLIED>
<!ATTLIST filter maxPosAsterisk CDATA  #IMPLIED>
<!ATTLIST filter maxPosQuestion CDATA  #IMPLIED>
<!ATTLIST filter maxFractionAsterisk CDATA  #IMPLIED>

<!ATTLIST filter generateWordParts  CDATA  #IMPLIED>
<!ATTLIST filter generateNumberParts CDATA  #IMPLIED>
<!ATTLIST filter catenateWords  CDATA  #IMPLIED>
<!ATTLIST filter catenateNumbers  CDATA  #IMPLIED>
<!ATTLIST filter catenateAll  CDATA  #IMPLIED>
<!ATTLIST filter splitOnCaseChange  CDATA  #IMPLIED>
<!ATTLIST filter preserveOriginal  CDATA  #IMPLIED>


<!ATTLIST filter pattern  CDATA  #IMPLIED>
<!ATTLIST filter replacement  CDATA  #IMPLIED>
<!ATTLIST filter replace  CDATA  #IMPLIED>
<!ATTLIST filter min  CDATA  #IMPLIED>
<!ATTLIST filter max  CDATA  #IMPLIED>
<!ATTLIST filter encoder  CDATA  #IMPLIED>




<!ELEMENT sharedKey (#PCDATA)>
<!ELEMENT uniqueKey (#PCDATA)>
<!ELEMENT defaultSearchField (#PCDATA)>

<!ELEMENT similarity (str*)>
<!ATTLIST similarity class CDATA #REQUIRED>

<!ELEMENT str (#PCDATA)>
<!ATTLIST str name CDATA #REQUIRED>


<!ELEMENT solrQueryParser EMPTY>
<!ATTLIST solrQueryParser defaultOperator (OR|AND) #REQUIRED>

<!ELEMENT fields (field|dynamicField)+>
<!ELEMENT field  EMPTY>
<!ATTLIST field  name CDATA #REQUIRED>
<!ATTLIST field  type CDATA #REQUIRED>
<!ATTLIST field  indexed (true|false) #IMPLIED>
<!ATTLIST field  stored (true|false) #IMPLIED>
<!ATTLIST field  multiValued (true|false) #IMPLIED>
<!ATTLIST field  required (true|false) #IMPLIED>
<!ATTLIST field  default CDATA #IMPLIED>
<!ATTLIST field  omitTermFreqAndPositions  (true|false)  #IMPLIED>
<!ATTLIST field  omitPositions  (true|false)  #IMPLIED>
<!ATTLIST field  termVectors  (true|false)  #IMPLIED>
<!ATTLIST field  termPositions  (true|false)  #IMPLIED>
<!ATTLIST field  termOffsets  (true|false)  #IMPLIED>
<!ATTLIST field  termPayloads  (true|false)  #IMPLIED>
<!ATTLIST field  docValues    (true|false)  #IMPLIED>


<!ATTLIST field  useDocValuesAsStored (true|false)  #IMPLIED>


<!ELEMENT dynamicField  EMPTY>
<!ATTLIST dynamicField  name CDATA #REQUIRED>
<!ATTLIST dynamicField  type CDATA #REQUIRED>
<!ATTLIST dynamicField  indexed (true|false) #IMPLIED>
<!ATTLIST dynamicField  stored (true|false) #IMPLIED>
<!ATTLIST dynamicField  multiValued (true|false) #IMPLIED>
<!ATTLIST dynamicField  required (true|false) #IMPLIED>
<!ATTLIST dynamicField  docValues    (true|false)  #IMPLIED>
<!ATTLIST dynamicField  default CDATA #IMPLIED>

<!ELEMENT copyField EMPTY>
<!ATTLIST copyField  source CDATA #REQUIRED>
<!ATTLIST copyField  dest CDATA #REQUIRED>

=== Celebrate-future/tis/tis-console/src/test/resources/com/qlangtech/tis/config/module/action/s4employee_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~   or more contributor license agreements.  See the NOTICE file
  ~   distributed with this work for additional information
  ~   regarding copyright ownership.  The ASF licenses this file
  ~   to you under the Apache License, Version 2.0 (the
  ~   "License"); you may not use this file except in compliance
  ~   with the License.  You may obtain a copy of the License at
  ~
  ~       http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~   Unless required by applicable law or agreed to in writing, software
  ~   distributed under the License is distributed on an "AS IS" BASIS,
  ~   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~   See the License for the specific language governing permissions and
  ~   limitations under the License.
  -->

<!DOCTYPE schema SYSTEM "solrres://tisrepository/dtd/solrschema.dtd">
<schema name="template" version="1.5">
  <types>
    <fieldType name="string" class="solr.StrField" sortMissingLast="true" omitNorms="true" omitTermFreqAndPositions="true" />
    <fieldType name="int" class="solr.IntPointField" docValues="false" />
    <fieldType name="float" class="solr.FloatPointField" docValues="false" />
    <fieldType name="long" class="solr.LongPointField" docValues="false" />
    <fieldType name="double" class="solr.DoublePointField" docValues="false" />
    <fieldType name="date" class="com.qlangtech.tis.solrextend.fieldtype.TisDateField" docValues="false" />
    <fieldType name="timestamp" class="com.qlangtech.tis.solrextend.fieldtype.TisTimestampField" docValues="false" />
    <fieldType name="bitwise" class="com.qlangtech.tis.solrextend.fieldtype.BitwiseField" omitNorms="true" omitTermFreqAndPositions="true" />
    <fieldType name="ik" class="solr.TextField" autoGeneratePhraseQueries="false" omitNorms="true" omitTermFreqAndPositions="false">
      <analyzer type="query">
        <tokenizer class="com.qlangtech.tis.solrextend.fieldtype.st.STConvertTokenizerFactory" />
        <filter class="com.qlangtech.tis.solrextend.analyzer.IKTokenFilterFactory" />
        <filter class="solr.LowerCaseFilterFactory" />
        <filter class="solr.TrimFilterFactory" />
      </analyzer>
      <analyzer type="index">
        <tokenizer class="com.qlangtech.tis.solrextend.fieldtype.st.STConvertTokenizerFactory" />
        <filter class="com.qlangtech.tis.solrextend.analyzer.IKTokenFilterFactory" />
      </analyzer>
    </fieldType>
    <fieldType name="text_ws" class="solr.TextField" sortMissingLast="true" omitNorms="true" autoGeneratePhraseQueries="false" omitTermFreqAndPositions="true">
      <analyzer>
        <tokenizer class="solr.WhitespaceTokenizerFactory" />
      </analyzer>
    </fieldType>
    <fieldType name="like" class="solr.TextField" sortMissingLast="true" omitNorms="true" autoGeneratePhraseQueries="false" omitTermFreqAndPositions="true">
      <analyzer type="index">
        <tokenizer class="solr.NGramTokenizerFactory" minGramSize="2" maxGramSize="7" />
        <filter class="solr.LowerCaseFilterFactory" />
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.WhitespaceTokenizerFactory" />
        <filter class="solr.LowerCaseFilterFactory" />
      </analyzer>
    </fieldType>
    <fieldType name="pinyin" class="solr.TextField" positionIncrementGap="100" autoGeneratePhraseQueries="false" omitNorms="true" omitPositions="true">
      <analyzer type="index">
        <tokenizer class="solr.PatternTokenizerFactory" pattern=",\s*" />
        <filter class="solr.NGramFilterFactory" minGramSize="1" maxGramSize="7" />
        <filter class="solr.LowerCaseFilterFactory" />
        <filter class="solr.TrimFilterFactory" />
        <filter class="com.qlangtech.tis.solrextend.fieldtype.pinyin.PinyinTokenFilterFactory" />
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.PatternTokenizerFactory" pattern=",\s*" />
        <filter class="solr.LowerCaseFilterFactory" />
      </analyzer>
    </fieldType>
    <fieldType name="test" class="plugin:test" positionIncrementGap="0" />
  </types>
  <fields>
    <field name="emp_no" type="string" stored="true" indexed="true" docValues="true" multiValued="false" />
    <field name="birth_date" type="date" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="first_name" type="test" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="last_name" type="string" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="gender" type="string" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="hire_date" type="timestamp" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="_version_" type="long" stored="true" indexed="false" docValues="true" multiValued="false" />
    <field name="text" type="string" stored="false" indexed="true" docValues="false" multiValued="true" />
    <dynamicField name="json_*" type="string" stored="true" indexed="true" docValues="true" multiValued="false" />
  </fields>
  <uniqueKey>emp_no</uniqueKey>
  <sharedKey>emp_no</sharedKey>
</schema>

=== Celebrate-future/tis/tis-console/src/test/resources/com/qlangtech/tis/solrdao/s4totalpay-schema-already-contain-fieldtype-plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--~
  ~   Licensed to the Apache Software Foundation (ASF) under one
  ~   or more contributor license agreements.  See the NOTICE file
  ~   distributed with this work for additional information
  ~   regarding copyright ownership.  The ASF licenses this file
  ~   to you under the Apache License, Version 2.0 (the
  ~   "License"); you may not use this file except in compliance
  ~   with the License.  You may obtain a copy of the License at
  ~
  ~       http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~   Unless required by applicable law or agreed to in writing, software
  ~   distributed under the License is distributed on an "AS IS" BASIS,
  ~   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~   See the License for the specific language governing permissions and
  ~   limitations under the License.
  -->

<!DOCTYPE schema SYSTEM    "solrres://tisrepository/dtd/solrschema.dtd">
<schema name="search4dfireOrderInfo" version="1.5">
    <types>
        <fieldType name="string" class="solr.StrField" sortMissingLast="true" omitNorms="true"
                   omitTermFreqAndPositions="true"/>
        <fieldType name="test" class="plugin:test" precisionStep="0" positionIncrementGap="0" sortMissingLast="true"/>
    </types>
    <fields>

        <field name="totalpay_id" type="string" stored="true" indexed="true" required="true" docValues="true"/>
        <field name="curr_date" type="test" stored="true" indexed="true" docValues="true" required="false"/>
    </fields>
    <sharedKey>entity_id</sharedKey>
    <uniqueKey>totalpay_id</uniqueKey>
</schema>
